### ISSUE TITLE
Max Craftsmanship calculates wrong

### ISSUE THREAD

**Issue by nt153133** [Igie/FFXIV-Crafting-Sim#1]
In FFXIVCraftingSim\Types\RecipeSolutionInfo.cs
Line #124
`while (s.CurrentProgress >= recipeProgress)` should be `while (s.CurrentProgress > recipeProgress)`
For sandteak lumber with stats 2480/2499/541 non-spec it would generate these rotations
![image](https://user-images.githubusercontent.com/52430037/85629004-133a3c80-b63f-11ea-995d-17f32e314931.png)
You physically can't get past the 4th `Delicate Synthesis` the craft hits exact progress and finishes. If the condition is changed to `>`
the simulator generates correct rotations like:
![image](https://user-images.githubusercontent.com/52430037/85629185-63b19a00-b63f-11ea-93b6-bcdab4faa57c.png)

**Comment by Igie** [comment]
Right, while finding minimum stats, current progress can't get below max progress, thanks for noticing
It's actually the same for control, I'll fix it asap
